pbr as a test-requirement
Avoid the issue with pbr being fetched by easy_install and causing
TypeError: object.__new__(Markup) is not safe, use unicode.__new__()
Relevant info: https://bugs.launchpad.net/pbr/+bug/1384919